//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NavigationUnity
{
    [Serializable]
    public class NavigationTaskDefinitionMsg : Message
    {
        public const string k_RosMessageName = "navigation_unity_msgs/NavigationTaskDefinition";
        public override string RosMessageName => k_RosMessageName;

        public string task_type;
        public float task_seconds;
        public float task_elapsed_seconds;

        public NavigationTaskDefinitionMsg()
        {
            this.task_type = "";
            this.task_seconds = 0.0f;
            this.task_elapsed_seconds = 0.0f;
        }

        public NavigationTaskDefinitionMsg(string task_type, float task_seconds, float task_elapsed_seconds)
        {
            this.task_type = task_type;
            this.task_seconds = task_seconds;
            this.task_elapsed_seconds = task_elapsed_seconds;
        }

        public static NavigationTaskDefinitionMsg Deserialize(MessageDeserializer deserializer) => new NavigationTaskDefinitionMsg(deserializer);

        private NavigationTaskDefinitionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_type);
            deserializer.Read(out this.task_seconds);
            deserializer.Read(out this.task_elapsed_seconds);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_type);
            serializer.Write(this.task_seconds);
            serializer.Write(this.task_elapsed_seconds);
        }

        public override string ToString()
        {
            return "NavigationTaskDefinitionMsg: " +
            "\ntask_type: " + task_type.ToString() +
            "\ntask_seconds: " + task_seconds.ToString() +
            "\ntask_elapsed_seconds: " + task_elapsed_seconds.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
