//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NavigationUnity
{
    [Serializable]
    public class ResetWorldResponse : Message
    {
        public const string k_RosMessageName = "navigation_unity_msgs/ResetWorld";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public ResetWorldResponse()
        {
            this.success = false;
        }

        public ResetWorldResponse(bool success)
        {
            this.success = success;
        }

        public static ResetWorldResponse Deserialize(MessageDeserializer deserializer) => new ResetWorldResponse(deserializer);

        private ResetWorldResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "ResetWorldResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
